#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

PROG="pathseq-t2t"
VERSION="0.3.0"

# Load libs if present
SCRIPT_DIR="${SCRIPT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)}"
LIB_DIR="${SCRIPT_DIR%/src}/lib"
[ -f "${LIB_DIR}/logging.sh" ] && . "${LIB_DIR}/logging.sh"
[ -f "${LIB_DIR}/utils.sh" ] && . "${LIB_DIR}/utils.sh"


# ---------- Output dir defaults & helpers ----------
OUTDIR_DEFAULT="./pst2t_out"
OUTDIR="${OUTDIR:-$OUTDIR_DEFAULT}"

_set_outdirs() {
  OUTDIR_BAMS="${OUTDIR}/bams"
  OUTDIR_FILTER="${OUTDIR}/filter_stats"
  OUTDIR_CLASSIFY="${OUTDIR}/classification_stats"
  OUTDIR_RESULTS="${OUTDIR}/results"
  OUTDIR_ASSEMBLY="${OUTDIR}/assembly"
}
_set_outdirs


usage() {
  cat <<EOF
${PROG} ${VERSION}

Usage:
  ${PROG} <command> [options]

Commands:
  filter      --input-bam <bam> --aligner <bwa|dragen> --decoys-to-mask <bed|None> [--sample-id <id>] [--outdir <dir>]
  prefilter   --input-bam <bam> --aligner <bwa|dragen> --decoys-to-mask <bed|None> \\
              [--sample-id <id>] [--outdir <dir>] [--unaligned-out <bam>] [--decoys-out <bam>] [--flagstat-out <tsv>]
  qcfilter    [--sample-id <id>] [--input-unaligned <bam>] [--input-decoys <bam>] \\
              ([--hostdir <dir>] or \$HOSTDIR)
  t2tfilter   [--sample-id <id>] [--input-paired <bam>] [--input-unpaired <bam>] \\
              ([--reference <t2t.fa>] or \$T2TREF) [--decoys-to-mask <bed|None>]
  classify    [--sample-id <id>] [--input-paired <bam>] [--input-unpaired <bam>] \\
              [--classifiers kraken|metaphlan|sylph]
  assemble    --input-unaligned <bam> [--input-decoys <bam>] [--sample-id <id>] [--outdir <dir>]
  binqc       [--sample-id <id>] [--outdir <dir>] [--assembly-dir <dir>] [--bins-dir <dir>] [--qc-dir <dir>] [--model <both|checkm2|checkv>]
  binclassify [--sample-id <id>] [--outdir <dir>] [--assembly-dir <dir>] [--bins-dir <dir>] [--classify-dir <dir>]
  summarize   --sample-id <id> [--outdir <dir>] [--results-dir <dir>]
  summarize-assembly --sample-id <id> [--outdir <dir>] [--assembly-dir <dir>] [--results-dir <dir>]

Global options:
  -h, --help      Show this help
  --version       Print version

Examples:
  ${PROG} filter --input-bam input.bam --aligner bwa --decoys-to-mask pathseq-t2t/non_human_decoys.bed \\
                 --sample-id input --hostdir /refs/pathseq_host --reference t2t.fa
  ${PROG} prefilter --input-bam input.bam --aligner bwa --decoys-to-mask pathseq-t2t/non_human_decoys.bed
  ${PROG} qcfilter --input-unaligned pst2t_out/bams/input.unaligned.bam \\
                   --input-decoys pst2t_out/bams/input.decoys.bam
  ${PROG} t2tfilter --input-paired pst2t_out/bams/input.qcfilt_paired.bam \\
                    --input-unpaired pst2t_out/bams/input.qcfilt_unpaired.bam \\
                    --reference t2t.fa
  ${PROG} classify --input-paired pst2t_out/bams/input.t2tfilt_paired.bam \\
                   --input-unpaired pst2t_out/bams/input.t2tfilt_unpaired.bam \\
                   --classifiers kraken,metaphlan,sylph
  ${PROG} assemble --input-unaligned pst2t_out/bams/input.prefilter.unaligned.bam \\
                   --input-decoys pst2t_out/bams/input.prefilter.decoys.bam \\
                   --sample-id input
  ${PROG} binqc --sample-id input --outdir pst2t_out
  ${PROG} binclassify --sample-id input --outdir pst2t_out
  ${PROG} summarize --sample-id input --outdir pst2t_out --results-dir pst2t_out/results
EOF
}

# --- Global flag handling ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    -q|--quiet)   log_level=0; shift ;;
    -v|--verbose) log_level=$(( ${log_level:-1} + 1 )); shift ;;
    -h|--help)    usage; exit 0 ;;
    --version)    echo "${PROG} ${VERSION}"; exit 0 ;;
    --) shift; break ;;
    -*)
      die "Unknown global option: $1"
      ;;
    *) break ;;
  esac
done


cmd="${1:-}"
[[ -z "${cmd}" ]] && { usage; exit 2; }
shift || true


# ---------------------------- helpers ----------------------------
[ -f "${LIB_DIR}/requirements.sh" ] && . "${LIB_DIR}/requirements.sh"
[ -f "${LIB_DIR}/io.sh" ] && . "${LIB_DIR}/io.sh"

# ---------------------------- Commands ----------------------------
CMD_DIR="${SCRIPT_DIR%/src}/src/commands"
for _cmd_file in \
  "${CMD_DIR}/filter.sh" \
  "${CMD_DIR}/prefilter.sh" \
  "${CMD_DIR}/qcfilter.sh" \
  "${CMD_DIR}/t2tfilter.sh" \
  "${CMD_DIR}/classify.sh" \
  "${CMD_DIR}/assemble.sh" \
  "${CMD_DIR}/binqc.sh" \
  "${CMD_DIR}/binclassify.sh" \
  "${CMD_DIR}/summarize.sh" \
  "${CMD_DIR}/summarize-assembly.sh"
do
  [ -f "${_cmd_file}" ] && . "${_cmd_file}"
done
unset _cmd_file
# ---------------------------- Dispatcher ----------------------------
case "${cmd}" in
  filter)      cmd_filter "$@" ;;
  prefilter)   cmd_prefilter "$@" ;;
  qcfilter)    cmd_qcfilter "$@" ;;
  t2tfilter)   cmd_t2tfilter "$@" ;;
  classify)    cmd_classify "$@" ;;
  assemble)    cmd_assemble "$@" ;;
  binqc)       cmd_binqc "$@" ;;
  binclassify) cmd_binclassify "$@" ;;
  summarize)            cmd_summarize "$@" ;;
  summarize-assembly)   cmd_summarize_assembly "$@" ;;
  -h|--help|help) usage ;;
  *) die "Unknown command: ${cmd}. Run '${PROG} --help' for usage." ;;
esac
